:Author: ns0104
:Email: {AuthorEmail}
:Date: 07/12/2022
:Revision: version#
:License: Public Domain

= Project: {Project}

Describe your project

== Step 1: Installation
This project runs through the Arduino IDE or Web Editor, SQL Server 2019 as well as Visual Studio 2022 which will need to be installed.

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch, or use an arduino base sensor kit which comes pre-assembled and ready for use once an Arduino Uno is attatched. 

== Step 3: Load the code

Upload the code contained in this sketch on to your board and run it through Visual Studio connected to a SQL Server Database.

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under no License.

=== Contributing
To contribute to this project please contact ns0104 https://id.arduino.cc/ns0104

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name                   | Part number | Quantity
| R1 | 10k Resistor                | 1234-abcd   | 10
| L1 | Red LED                     | 2345-asdf   | 5
| A1 | Arduino Zero                | ABX00066    | 1
| A0 | Arduino Sensor Kit - Base   | TPX00031    | 1
| A2 | Arduino Uno Rev.3           | A000066     | 1
| C1 | USB 2.0 Cable Type A/B      | M000006     | 1
|===

While Parts R1, L1, and A1 would work, we did not use them and only used parts from A0 down.


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
